# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/calcs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/calcs.proto\x12\x05\x63\x61lcs\">\n\x0f\x42haskaraRequest\x12\r\n\x05var_a\x18\x01 \x01(\x05\x12\r\n\x05var_b\x18\x02 \x01(\x05\x12\r\n\x05var_c\x18\x03 \x01(\x05\"$\n\nRootsReply\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02x2\x18\x02 \x01(\x02\"0\n\x10\x46ibonacciRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\r\n\x05\x64\x65lay\x18\x02 \x01(\x05\"\x1f\n\x0e\x46ibonacciReply\x12\r\n\x05value\x18\x01 \x01(\x05\x32\x87\x01\n\x05\x43\x61lcs\x12:\n\x0bGetBhaskara\x12\x16.calcs.BhaskaraRequest\x1a\x11.calcs.RootsReply\"\x00\x12\x42\n\x0cGetFibonacci\x12\x17.calcs.FibonacciRequest\x1a\x15.calcs.FibonacciReply\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.calcs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BHASKARAREQUEST._serialized_start=28
  _BHASKARAREQUEST._serialized_end=90
  _ROOTSREPLY._serialized_start=92
  _ROOTSREPLY._serialized_end=128
  _FIBONACCIREQUEST._serialized_start=130
  _FIBONACCIREQUEST._serialized_end=178
  _FIBONACCIREPLY._serialized_start=180
  _FIBONACCIREPLY._serialized_end=211
  _CALCS._serialized_start=214
  _CALCS._serialized_end=349
# @@protoc_insertion_point(module_scope)
