# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import calculations_pb2 as proto_dot_calculations__pb2


class CalculationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRootsEquationByBhaskara = channel.unary_unary(
                '/calculations.Calculations/GetRootsEquationByBhaskara',
                request_serializer=proto_dot_calculations__pb2.BhaskaraRequest.SerializeToString,
                response_deserializer=proto_dot_calculations__pb2.RootsEquationReply.FromString,
                )
        self.GetFibonacciSequence = channel.unary_stream(
                '/calculations.Calculations/GetFibonacciSequence',
                request_serializer=proto_dot_calculations__pb2.FibonacciSequenceRequest.SerializeToString,
                response_deserializer=proto_dot_calculations__pb2.FibonacciSequenceReply.FromString,
                )


class CalculationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRootsEquationByBhaskara(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFibonacciSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRootsEquationByBhaskara': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRootsEquationByBhaskara,
                    request_deserializer=proto_dot_calculations__pb2.BhaskaraRequest.FromString,
                    response_serializer=proto_dot_calculations__pb2.RootsEquationReply.SerializeToString,
            ),
            'GetFibonacciSequence': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFibonacciSequence,
                    request_deserializer=proto_dot_calculations__pb2.FibonacciSequenceRequest.FromString,
                    response_serializer=proto_dot_calculations__pb2.FibonacciSequenceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculations.Calculations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRootsEquationByBhaskara(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculations.Calculations/GetRootsEquationByBhaskara',
            proto_dot_calculations__pb2.BhaskaraRequest.SerializeToString,
            proto_dot_calculations__pb2.RootsEquationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFibonacciSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/calculations.Calculations/GetFibonacciSequence',
            proto_dot_calculations__pb2.FibonacciSequenceRequest.SerializeToString,
            proto_dot_calculations__pb2.FibonacciSequenceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
