# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import calcs_pb2 as proto_dot_calcs__pb2


class CalcsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBhaskara = channel.unary_unary(
                '/calcs.Calcs/GetBhaskara',
                request_serializer=proto_dot_calcs__pb2.BhaskaraRequest.SerializeToString,
                response_deserializer=proto_dot_calcs__pb2.RootsReply.FromString,
                )
        self.GetFibonacci = channel.unary_stream(
                '/calcs.Calcs/GetFibonacci',
                request_serializer=proto_dot_calcs__pb2.FibonacciRequest.SerializeToString,
                response_deserializer=proto_dot_calcs__pb2.FibonacciReply.FromString,
                )


class CalcsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBhaskara(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFibonacci(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalcsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBhaskara': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBhaskara,
                    request_deserializer=proto_dot_calcs__pb2.BhaskaraRequest.FromString,
                    response_serializer=proto_dot_calcs__pb2.RootsReply.SerializeToString,
            ),
            'GetFibonacci': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFibonacci,
                    request_deserializer=proto_dot_calcs__pb2.FibonacciRequest.FromString,
                    response_serializer=proto_dot_calcs__pb2.FibonacciReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calcs.Calcs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calcs(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBhaskara(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calcs.Calcs/GetBhaskara',
            proto_dot_calcs__pb2.BhaskaraRequest.SerializeToString,
            proto_dot_calcs__pb2.RootsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFibonacci(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/calcs.Calcs/GetFibonacci',
            proto_dot_calcs__pb2.FibonacciRequest.SerializeToString,
            proto_dot_calcs__pb2.FibonacciReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
